"""empty message

Revision ID: 4ae37809c23e
Revises: eae0d7060968
Create Date: 2020-02-09 02:47:46.785343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ae37809c23e'
down_revision = 'eae0d7060968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.public_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cart')
    op.add_column('cart_item', sa.Column('cart', sa.String(length=100), nullable=False))
    op.add_column('cart_item', sa.Column('item_id', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'cart_item', ['item_id'])
    op.create_foreign_key(None, 'cart_item', 'item', ['item_id'], ['public_id'])
    op.create_foreign_key(None, 'cart_item', 'cart_table', ['cart'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_item', type_='foreignkey')
    op.drop_constraint(None, 'cart_item', type_='foreignkey')
    op.drop_constraint(None, 'cart_item', type_='unique')
    op.drop_column('cart_item', 'item_id')
    op.drop_column('cart_item', 'cart')
    op.create_table('cart',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cart_pkey')
    )
    op.drop_table('cart_table')
    # ### end Alembic commands ###
