"""empty message

Revision ID: 50dd323b2f1b
Revises: ddbf978efcd9
Create Date: 2020-02-09 00:22:36.058556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50dd323b2f1b'
down_revision = 'ddbf978efcd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('cart_id', sa.String(length=100), nullable=True),
    sa.Column('item_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.user_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.public_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_item')
    # ### end Alembic commands ###
