"""empty message

Revision ID: 65ee5e3e7609
Revises: 1c0a4c677aa0
Create Date: 2020-02-09 02:36:11.031012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65ee5e3e7609'
down_revision = '1c0a4c677aa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.public_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('cart_id', sa.String(length=100), nullable=False),
    sa.Column('item_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.user_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.public_id'], ),
    sa.PrimaryKeyConstraint('id', 'cart_id', 'item_id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_unique_constraint(None, 'user', ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_table('cart_item')
    op.drop_table('cart')
    # ### end Alembic commands ###
