"""all new cart

Revision ID: b5191003f367
Revises: 4961ffd831b0
Create Date: 2020-02-08 23:26:50.422232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5191003f367'
down_revision = '4961ffd831b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('size', sa.Integer(), nullable=True))
    op.alter_column('cart', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('cart', 'size')
    # ### end Alembic commands ###
