"""all new cart

Revision ID: dfb5100dfd45
Revises: f7c4703e767e
Create Date: 2020-02-09 01:09:23.601305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb5100dfd45'
down_revision = 'f7c4703e767e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('piece', sa.String(length=50), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('size', sa.String(length=10), nullable=False),
    sa.Column('available', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('cart_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('cart_id', sa.String(length=100), nullable=False),
    sa.Column('item_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.user_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.public_id'], ),
    sa.PrimaryKeyConstraint('id', 'cart_id', 'item_id'),
    sa.UniqueConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_item')
    op.drop_table('item')
    # ### end Alembic commands ###
