"""empty message

Revision ID: f42fc3f29ebe
Revises: f2cffb334fc2
Create Date: 2020-02-09 02:57:31.877233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42fc3f29ebe'
down_revision = 'f2cffb334fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('user_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'cart', ['user_id'])
    op.create_foreign_key(None, 'cart', 'user', ['user_id'], ['public_id'])
    op.add_column('cart_item', sa.Column('cart_id', sa.String(length=100), nullable=False))
    op.add_column('cart_item', sa.Column('item_id', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'cart_item', ['item_id'])
    op.create_foreign_key(None, 'cart_item', 'cart', ['cart_id'], ['user_id'])
    op.create_foreign_key(None, 'cart_item', 'item', ['item_id'], ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_item', type_='foreignkey')
    op.drop_constraint(None, 'cart_item', type_='foreignkey')
    op.drop_constraint(None, 'cart_item', type_='unique')
    op.drop_column('cart_item', 'item_id')
    op.drop_column('cart_item', 'cart_id')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='unique')
    op.drop_column('cart', 'user_id')
    # ### end Alembic commands ###
